[package]
name = "lspcat"
edition = "2021"

[dependencies]
tower-lsp = { version = "*", features = [
  "runtime-agnostic",
], default-features = false }
serde_json = "*"
dashmap = "*"
smol = "*"
lexopt = "*"
const_format = "*"
fauxgen = "*"
